function [fitresult, gof] = createFroudeFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'curvefit' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jan-2023 09:55:13


%% Fit: 'curvefit'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly3' );
excludedPoints = yData < -0.03; %this is just a guess rightnow
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
h = plot( fitresult, 'predobs')
%set(h,{'DisplayName'},{'curvefit','Lower bounds','Upper bounds'});



